#!/bin/bash
# =============================================================================
#  build-solution.sh  (v2 - pac instalado via dotnet tool)
#  Compila el PCF y genera el ZIP listo para importar en Power Apps
#  Uso: bash build-solution.sh
# =============================================================================
set -e

SOLUTION_NAME="MineroSuiteTabulatorSolution"
PUBLISHER_NAME="MineroSuite"
PUBLISHER_PREFIX="ms"
PCF_DIR="$(pwd)"
SOLUTION_DIR="/tmp/${SOLUTION_NAME}"

echo ""
echo "=== TabulatorControl PCF — Build & Package v2 ==="
echo ""

# ── PASO 1: Verificar Node, npm, dotnet ──────────────────────────────────────
echo "[1/7] Verificando herramientas..."
node --version && echo "  OK: Node.js"
npm --version  && echo "  OK: npm"
dotnet --version && echo "  OK: .NET"

# ── Instalar pac CLI via dotnet tool (forma correcta en Linux/Codespaces) ────
if ! command -v pac &> /dev/null; then
  echo "  pac no encontrado, instalando via dotnet tool..."
  dotnet tool install --global Microsoft.PowerApps.CLI.Tool
  # Agregar dotnet tools al PATH si no está
  export PATH="$PATH:$HOME/.dotnet/tools"
fi

# Asegurar que dotnet tools esté en PATH
export PATH="$PATH:$HOME/.dotnet/tools"

if command -v pac &> /dev/null; then
  echo "  OK: pac $(pac --version | head -1)"
else
  echo "  WARN: pac no disponible en PATH, continuando sin solución..."
  USE_PAC=false
fi

# ── PASO 2: npm install ───────────────────────────────────────────────────────
echo ""
echo "[2/7] Instalando dependencias npm..."
npm install
echo "  OK"

# ── PASO 3: Crear ManifestTypes.d.ts ─────────────────────────────────────────
echo ""
echo "[3/7] Creando ManifestTypes.d.ts..."
mkdir -p TabulatorControl/generated

cat > TabulatorControl/generated/ManifestTypes.d.ts << 'MANIFEST_EOF'
/*
 * Generated by pcf-scripts — DO NOT EDIT manually
 */

export interface IInputs {
  dataJson: ComponentFramework.PropertyTypes.StringProperty;
  configJson: ComponentFramework.PropertyTypes.StringProperty;
}

export interface IOutputs {
  selectedRow?: string;
}
MANIFEST_EOF

echo "  OK: ManifestTypes.d.ts creado"

# ── PASO 4: Build PCF ─────────────────────────────────────────────────────────
echo ""
echo "[4/7] Compilando PCF (npm run build)..."
npm run build
echo "  OK: PCF compilado"

# ── PASO 5: Inicializar solución ──────────────────────────────────────────────
echo ""
echo "[5/7] Inicializando solución Power Apps..."
rm -rf "${SOLUTION_DIR}"
mkdir -p "${SOLUTION_DIR}"
cd "${SOLUTION_DIR}"

pac solution init \
  --publisher-name "${PUBLISHER_NAME}" \
  --publisher-prefix "${PUBLISHER_PREFIX}" \
  --outputDirectory .
echo "  OK: Solución inicializada"

# ── PASO 6: Agregar referencia al PCF ────────────────────────────────────────
echo ""
echo "[6/7] Agregando referencia al PCF..."
pac solution add-reference --path "${PCF_DIR}"
echo "  OK"

# ── PASO 7: Build con dotnet ──────────────────────────────────────────────────
echo ""
echo "[7/7] Compilando solución (dotnet build)..."
dotnet build --configuration Release

# Buscar el ZIP
ZIP_FOUND=$(find . -name "*.zip" -not -path "*/obj/*" | head -1)

if [ -n "$ZIP_FOUND" ]; then
  cp "${ZIP_FOUND}" "${PCF_DIR}/${SOLUTION_NAME}.zip"
  echo ""
  echo "================================================================="
  echo "  OK: ZIP listo en: ${PCF_DIR}/${SOLUTION_NAME}.zip"
  echo ""
  echo "  Para descargar:"
  echo "  1. Explorer (panel izq) -> clic derecho en el .zip -> Download"
  echo ""
  echo "  Para importar en Power Apps:"
  echo "  make.powerapps.com -> Soluciones -> Importar solucion -> ZIP"
  echo "================================================================="
else
  echo "ERROR: No se encontro el ZIP. Archivos en bin/:"
  find . -name "*.zip" 2>/dev/null || echo "  (ninguno)"
  exit 1
fi
