#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════════
#  setup.sh — Instalación automática en GitHub Codespaces
#  Se ejecuta automáticamente al crear el Codespace (postCreateCommand)
# ══════════════════════════════════════════════════════════════════════════════
set -e

echo "╔══════════════════════════════════════════╗"
echo "║  TabulatorControl PCF — Setup Codespace  ║"
echo "╚══════════════════════════════════════════╝"

# ── 1. Power Platform CLI ────────────────────────────────────────────────────
echo ""
echo "📦 Instalando Power Platform CLI (pac)..."

# Instalar pac via npm (más rápido que el instalador oficial en Linux)
npm install -g @microsoft/powerapps-cli 2>/dev/null || true

# Alternativa: instalar via script oficial de Microsoft
if ! command -v pac &> /dev/null; then
  echo "  → Instalando pac via script oficial..."
  curl -s https://raw.githubusercontent.com/microsoft/powerplatform-build-tools/main/scripts/install-pac.sh | bash
fi

echo "  ✅ pac instalado: $(pac --version 2>/dev/null || echo 'via npm')"

# ── 2. Dependencias npm del proyecto ────────────────────────────────────────
echo ""
echo "📦 Instalando dependencias npm (Tabulator, pcf-scripts, TypeScript)..."
npm install
echo "  ✅ npm install completado"

# ── 3. Crear directorio generated con ManifestTypes ─────────────────────────
echo ""
echo "🔧 Creando ManifestTypes.d.ts..."
mkdir -p TabulatorControl/generated

cat > TabulatorControl/generated/ManifestTypes.d.ts << 'EOF'
/*
 * Generated by pcf-scripts — DO NOT EDIT manually
 * Re-generate with: npm run refreshTypes
 */

export interface IInputs {
  dataJson: ComponentFramework.PropertyTypes.StringProperty;
  configJson: ComponentFramework.PropertyTypes.StringProperty;
}

export interface IOutputs {
  selectedRow?: string;
}
EOF

echo "  ✅ ManifestTypes.d.ts creado"

# ── 4. Mensaje final ─────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✅ Entorno listo. Comandos disponibles:                     ║"
echo "║                                                              ║"
echo "║  npm run build        → Compilar el PCF                     ║"
echo "║  npm start            → Modo desarrollo (puerto 8181)        ║"
echo "║  bash build-solution.sh → Crear ZIP para Power Apps         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
