#!/bin/bash
# =============================================================================
#  setup.sh  (v2 - pac via dotnet tool, nombre de paquete correcto)
#  Se ejecuta automaticamente al crear el Codespace (postCreateCommand)
# =============================================================================
set -e

echo ""
echo "=== TabulatorControl PCF — Setup Codespace v2 ==="
echo ""

# ── 1. Instalar pac CLI via dotnet tool (forma correcta para Linux) ───────────
echo "[1/4] Instalando pac CLI (Power Platform CLI via dotnet tool)..."

if ! command -v pac &> /dev/null; then
  dotnet tool install --global Microsoft.PowerApps.CLI.Tool
  # Agregar al PATH permanentemente en bash
  echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> ~/.bashrc
  export PATH="$PATH:$HOME/.dotnet/tools"
  echo "  OK: pac instalado"
else
  echo "  OK: pac ya instalado: $(pac --version | head -1)"
fi

# Asegurar PATH para la sesion actual
export PATH="$PATH:$HOME/.dotnet/tools"

# ── 2. Dependencias npm ───────────────────────────────────────────────────────
echo ""
echo "[2/4] Instalando dependencias npm..."
npm install
echo "  OK: npm install completado"

# ── 3. Crear ManifestTypes.d.ts ───────────────────────────────────────────────
echo ""
echo "[3/4] Creando ManifestTypes.d.ts..."
mkdir -p TabulatorControl/generated

cat > TabulatorControl/generated/ManifestTypes.d.ts << 'MANIFEST_EOF'
/*
 * Generated by pcf-scripts — DO NOT EDIT manually
 * Re-generate with: npm run refreshTypes
 */

export interface IInputs {
  dataJson: ComponentFramework.PropertyTypes.StringProperty;
  configJson: ComponentFramework.PropertyTypes.StringProperty;
}

export interface IOutputs {
  selectedRow?: string;
}
MANIFEST_EOF

echo "  OK: ManifestTypes.d.ts creado"

# ── 4. Mensaje final ──────────────────────────────────────────────────────────
echo ""
echo "[4/4] Setup completado!"
echo ""
echo "================================================================="
echo "  Entorno listo. Comandos disponibles en la terminal:"
echo ""
echo "  npm run build          -> Compilar el PCF"
echo "  npm start              -> Modo desarrollo (puerto 8181)"
echo "  bash build-solution.sh -> Crear ZIP para Power Apps"
echo "================================================================="
echo ""
